### ISSUE TITLE
Make plugin work with modern Gradle dependencies declarations

### ISSUE THREAD

**Issue by chadlwilson** [getgauge/gauge-gradle-plugin#25]
The current version of the plugin (1.7.3) does not work correctly when your project declares dependencies in modern Gradle style, such as `implementation`, `testImplementation`, `testRuntimeOnly` etc.

You get classpath errors when Gauge runs, unless you use `compile`, `testCompile` etc.

**Comment by Apoorva-GA** [comment]
Works with `gauge-gradle-plugin` version [1.7.3](https://plugins.gradle.org/plugin/org.gauge)
