### ISSUE TITLE
Transfer - gauge gradle

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge-gradle-plugin#28]

**Comment by nehashri** [comment]
Use org.gauge namespace to publish the plugin instead.

**Comment by nehashri** [comment]
The decision to plublish the artifact as `org.gauge` was taken as the transfer of the plugin was not initiated. Please refer https://discuss.gradle.org/t/transfer-ownership-of-gauge-plugin/31099

**Comment by Apoorva-GA** [comment]
`gauge-gradle-plugin` is published [here](https://plugins.gradle.org/plugin/org.gauge).
