### ISSUE TITLE
Gradle gauge not working!

### ISSUE THREAD

**Issue by patmuk** [getgauge/gauge-gradle-plugin#3]
to reproduce:
1. $ gauge install java
2. create build.gradle with the content from the README
3. modify: line 24: 
`    implementation ('com.thoughtworks.gauge:gauge-java:+')`
instead of
`    'com.thoughtworks.gauge:gauge-java:+'`
4. $ gradle gauge

result:
* What went wrong:
Execution failed for task ':gauge'.
> Gauge or Java runner is not installed! Read http://getgauge.io/documentation/user/current/getting_started/download_and_install.html

**Comment by chadlwilson** [comment]
This was actually fixed by #26 (released in `v1.8.0`) and can be closed now - core issue was that it did not support `implementation` style dependencies prior to this; only `compile`, `testCompile` etc.

**Comment by patmuk** [comment]
Super!

**Comment by CreeTar** [comment]
Not fixed, the link is still 404.

**Comment by sriv** [comment]
@CreeTar - which link do you see a 404 for? If you could open a new issue with details, we can investigate further.
