### ISSUE TITLE
Clarify release process for plugin

### ISSUE THREAD

**Issue by chadlwilson** [getgauge/gauge-gradle-plugin#33]
The previous plugin maintainer was releasing this plugin to

- [Maven Central](https://search.maven.org/search?q=a:gauge-gradle-plugin)
- [Bintray](https://bintray.com/search?query=gauge-gradle-plugin)
- [GitHub releases](https://github.com/getgauge/gauge-gradle-plugin/releases) (older versions; zip-only)

Since the fix merged in #2 we now have ability to push to the Gradle plugin portal; which can also be used [with legacy buildscript/classpath style](https://plugins.gradle.org/plugin/org.gauge).

Do we need to continue releasing official versions to Maven Central and Bintray? If not; I think it would be good for us to remove the Maven Central badge from the README as well as clarify the history for users transitioning to the new plugin's ownership. Happy to submit a PR.

**Comment by nehashri** [comment]
Going forward, we will be releasing Gauge gradle plugin to the Gradle portal available [here](https://plugins.gradle.org/plugin/org.gauge).
The plugin will be released under `org.gauge`.
The Gradle plugin nightly versions will be released to bintray. This will be available [here](https://bintray.com/gauge/gauge-gradle-plugin/Nightly).
We will not be releasing the plugin to Github releases anymore.

We still have to update the readme and provide a migration path to the users. 
We will have to update our [gradle template](https://github.com/getgauge/gauge-repository/tree/master/templates/java_gradle) too.

**Comment by chadlwilson** [comment]
Sounds great; I can submit a PR to update the readme. I didn't realise there were Gradle templates in that repo - I can have a look at that as well if it helps 👍
