### ISSUE TITLE
Unable to run a scenario with line number

### ISSUE THREAD

**Issue by shubhamsc** [getgauge/gauge-gradle-plugin#39]
## Actual behaviour
When we try to run a scenario with line number as
```
./gradlew clean gauge -PspecsDir="specs/example.spec:13"
```
It fails with error: `Specs directory specified is not existing!` 

## Expected behaviour
It should run a scenario with a given line number without any error.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: `9e1a973`
