### ISSUE TITLE
Gauge or Java Runner is not installed! Error links returning 404

### ISSUE THREAD

**Issue by ed0906** [getgauge/gauge-gradle-plugin#43]
I am trying to run `./gradlew gauge` and the following exception is getting thrown

https://github.com/getgauge/gauge-gradle-plugin/blob/9e1a973908aa485be8774072b4405ff8937b8101/plugin/src/main/java/com/thoughtworks/gauge/gradle/GaugeTask.java#L53

The exception appears to mask an `IOException` making it difficult for me to debug as I cant see the true cause.
The URL also leads to a path that doesn't exist.

Would it be possible to propagate the cause of the exception e.g.

```
catch (IOException cause) {
            throw new GaugeExecutionFailedException("Gauge or Java runner is not installed! Read http://getgauge.io/documentation/user/current/getting_started/download_and_install.html", cause);
        }
```
Or alternatively to log out the IO Exception

And to update the URL it refers to to a page that exists.

#### Gauge Version
```
Gauge version: 1.0.6

Plugins
-------
html-report (4.0.8)
java (0.7.3)
screenshot (0.0.1)
```
Note that I do have both gauge and the java runner installed.

##### Gradle Version
6.1.1

##### Gradle Gauge Plugin Version
1.8.0

##### Gauge-Java Version
0.7.3

**Comment by negiDharmendra** [comment]
@ed0906 Please upgrade Gauge and Gauge Java to the latest version and see if you are still facing the issue.

**Comment by ed0906** [comment]
I solved this by downgrading to gauge-java 0.7.3.

It turns out 0.7.4 doesn't work with Kotlin any longer.

I still think it would be helpful if the actual IOException was logged by the plugin, at the moment it is very difficult to debug

**Comment by NivedhaSenthil** [comment]
Thanks for reporting I could replicate the issue with Kotlin .. we will be making a fix soon.

**Comment by NivedhaSenthil** [comment]
Fix for actual issue is done via https://github.com/getgauge/gauge-gradle-plugin/pull/44. Kotlin issue will be handled in issue https://github.com/getgauge/gauge-java/issues/390
